### PR TITLE
Allow Employers to publish & unpublish

### PR DESCRIPTION
**Pull request by godith0**
Issues:
- [x] accesses DB twice when checking for `published` status
- [x] `Continue setting up` button doesn't work
- [x] `Goto My Portfolio` works but isn't formatted properly (`router-link` may be overwriting behavior)

---
Small comment: first time Vue user, please forgive my bad style!

### CODE REVIEW

**Comment by godith0** [comment]
@dericklee510 should we change the "finish setup" button on the Portfolio page? If so, what should it be? Since it's on a separate page from "Bar", this could be an involved change.

**Comment by godith0** [comment]
@Juxsta i could be wrong, but i noticed that the prod db doesn't have a `publish` key but the dev db does. will we need to do a db migration or should I write my code to handle the error where `publish` isn't set?

**Comment by godith0** [comment]
> @dericklee510 should we change the "finish setup" button on the Portfolio page? If so, what should it be? Since it's on a separate page from "Bar", this could be an involved change.

Spoke w/ @dericklee510 just now and implemented the change. When a program has been published, the button will change to "Edit Program".

**Comment by godith0** [comment]
> @Juxsta i could be wrong, but i noticed that the prod db doesn't have a `publish` key but the dev db does. will we need to do a db migration or should I write my code to handle the error where `publish` isn't set?

Spoke w/ @Juxsta and we'll make sure to do a migration before merging into prod; but we'll go ahead and merge into `develop` now

**Review by dericklee510 — APPROVED** [review]
im good

**Pull request merged**
